import type { Metadata } from "next";
import localFont from "next/font/local"
import { Inter } from "next/font/google";
import "./globals.css";
const vazir = localFont({
  src: [
    {
      path: '/ui/fonts/shabnam/Shabnam-Medium-FD.woff2',
      weight: '400',
      style: 'normal',
    },
    // {
    //   path: '/ui/fonts/shab/IRANSans-web.woff2',
    //   weight: '700',
    //   style: 'normal',
    // },
    // سایر وزن‌های فونت...
  ],
  variable: '--font-vazir',
});
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazir.className}>{children}</body>
    </html>
  );
}
